apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: equivalent-swan-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: equivalent-swan-python 
  name: equivalent-swan-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: equivalent-swan-python 
